[package]
name = "webidl2wit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0"
heck = "0.5"
itertools = "0.13"
weedle = "0.13.0"
wit-encoder = { git = "https://github.com/bytecodealliance/wasm-tools.git" }

[dev-dependencies]
pretty_assertions = "1.4.0"
