name: create-release-pr
run-name: create-release-pr

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project to to prep for release (ex. `0.1.0`)
        required: true
        default: "webidl2wit"
        type: choice
        options:
          - webidl2wit
          - webidl2wit-cli

      version:
        description: Version to prep for release (ex. `0.1.0`, `0.1.0-rc.0`)
        required: true
        type: string

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    steps:
      # Checkout the full repository history
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      # Set up Rust dependencies
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7
      - name: Install cargo deps
        uses: taiki-e/install-action@d125c0a83576d3c0c86ac610c708b38d3565af4e # v2.47.15
        with:
          tool: >-
            just,
            git-cliff
      - uses: taiki-e/cache-cargo-install-action@caa6f48d18d42462f9c30df89e2b4f71a42b7c2c # v2.0.1
        with:
          tool: cargo-get
      - uses: taiki-e/cache-cargo-install-action@caa6f48d18d42462f9c30df89e2b4f71a42b7c2c # v2.0.1
        with:
          tool: cargo-edit

      - name: Gather metadata
        id: meta
        shell: bash
        env:
          NEXT_VERSION: ${{ inputs.version }}
          PROJECT: ${{ inputs.project }}
        run: |
          if [[ $NEXT_VERSION == v* ]]; then
            echo "::error::next version [$NEXT_VERSION] starts with 'v' -- enter only the semver version (ex. '0.1.0', not 'v0.1.0')";
            exit 1;
          fi
          export PROJECT=$(echo $PROJECT || echo "webidl")
          cd crates/$PROJECT
          export CURRENT_VERSION=$(cargo get package.version --terminator Nul)

          echo -e "project=$PROJECT" >> $GITHUB_OUTPUT
          echo -e "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo -e "next-version=$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Update crate version
        working-directory: crates/${{ steps.meta.outputs.project }}
        run: |
          cargo set-version -p ${{ steps.meta.outputs.project }} ${{ steps.meta.outputs.next-version }}

      - name: Generate changelog
        working-directory: crates/${{ steps.meta.outputs.project }}
        run: |
          git cliff \
            --repository=../../.git \
            --unreleased \
            --tag=${{ steps.meta.outputs.project }}-${{ steps.meta.outputs.next-version }} \
            --prepend=CHANGELOG.md

      - name: Create release prep PR
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        with:
          branch: prep-release-${{ steps.meta.outputs.project}}-v${{ steps.meta.outputs.next-version }}
          commit-message: |
            release: ${{ steps.meta.outputs.project }} v${{ steps.meta.outputs.next-version }}
          title: |
            release: ${{ steps.meta.outputs.project }} v${{ steps.meta.outputs.next-version }}
          labels: |
            release-pr
          assignees: |
            MendyBerger
          signoff: true
          body: |
            This is a release prep branch for `${{ steps.meta.outputs.project }}` release `v${{ steps.meta.outputs.next-version }}`.

            To ensure this release is ready to be merged:
              - [ ] Review the updated CHANGELOG(s)
              - [ ] Test release artifacts (if necessary)

            After merging this PR, please do the following:
              - [ ] Run the `tag-release` CI workflow (specifying the commit hash of this PR once fast-forwarded onto `main`)
              - [ ] Run the `release` CI workflow, which will use the release tag to make a proper release to GitHub and Crates.io

            See CHANGELOG for changes made to this release before it goes out.
